### ISSUE TITLE
RIOT on docker - missing documentation

### ISSUE THREAD

**Issue by sagile** [redis/riot#167]
Docker Hub https://hub.docker.com/r/riotx/riot does not have documentation.
The RIOT documentation page https://redis.github.io/riot/ just mentions that it is possible to run RIOT as a docker image via `docker run riotx/riot [OPTIONS] [COMMAND]`.

I tried to run RIOT via the following docker-compose-riot.yml file:

```
services:
  riot:
    image: riotx/riot:latest
    container_name: riot-tool
    volumes:
      - ./riot-config:/app/config
      - ./wait-for-it.sh:/wait-for-it.sh
    working_dir: /app/config
    entrypoint: ["/bin/sh", "-c"]
    command: |
      db-import "SELECT * FROM beers" --jdbc-url "jdbc:postgresql://postgres:5432/beersdb" --jdbc-username postgres --jdbc-password postgres json.set --keyspace redis.beers.model.Beer --key id
    environment:
      REDIS_URL: redis://redis:6379
```

But I see error “SELECT * FROM beers: line 0: db-import: not found” in the docker logs.
